/* Language packs for the plain-language layer and the page: en (English), hi (Hinglish), hd (Hindi). */
(function (root) {
  const J = root.J || (root.J = {});
  const listEn = a => a.length <= 1 ? a.join("") : a.slice(0, -1).join(", ") + " and " + a[a.length - 1];
  const listHi = a => a.length <= 1 ? a.join("") : a.slice(0, -1).join(", ") + " aur " + a[a.length - 1];
  const listHd = a => a.length <= 1 ? a.join("") : a.slice(0, -1).join(", ") + " और " + a[a.length - 1];

  const en = {
    list: listEn,
    planet: p => p, sign: s => s,
    HOUSE: {
      1: "your body, health, looks and confidence", 2: "money savings, family life and the way you speak",
      3: "courage, your own efforts, siblings and short trips", 4: "home, mother, property, vehicles and peace of mind",
      5: "studies, intelligence, children, love life and creativity", 6: "job/service, competition, loans, illness and enemies",
      7: "marriage, spouse and business partners", 8: "sudden events, in-laws' money, secrets, surgery and long-term health",
      9: "luck, father, teachers, religion and long journeys", 10: "career, work, reputation and status",
      11: "income, profits, friends and wishes coming true", 12: "expenses, foreign lands, sleep, isolation and spiritual life" },
    SHORT: { 1: "self & health", 2: "money & family", 3: "courage & siblings", 4: "home & mother", 5: "studies, children & love",
      6: "job, loans & illness", 7: "marriage & partners", 8: "sudden events & hidden matters", 9: "luck & father", 10: "career & status",
      11: "income & gains", 12: "expenses & foreign" },
    PLANET: { Sun: "confidence, father, government and authority", Moon: "mind, emotions, mother and public image",
      Mars: "energy, courage, property, brothers and anger", Mercury: "communication, studies, business and quick thinking",
      Jupiter: "wisdom, money growth, children, teachers and (for women) husband", Venus: "love, marriage, comforts, beauty, vehicles and art",
      Saturn: "hard work, discipline, delays, servants and long-term results", Rahu: "ambition, foreign things, technology, sudden and unusual events",
      Ketu: "detachment, spirituality, research and sudden breaks" },
    MAL: { Sun: "ego clashes and a dominating attitude", Mars: "arguments, anger or heat in the relationship/area",
      Saturn: "delays, seriousness, heavy responsibility (results come late but last)", Rahu: "confusion, unusual or unconventional situations, restlessness",
      Ketu: "dissatisfaction, distance or detachment", Moon: "emotional ups and downs", Mercury: "mixed results" },
    BEN: { Jupiter: "protection, wisdom and growth", Venus: "harmony, love and comfort", Mercury: "good communication and smart choices", Moon: "care and emotional support" },
    DIG: { Exalted: "at its strongest", Moolatrikona: "very strong", Own: "strong (in its own home)", "Great Friend": "comfortable", Friend: "fairly comfortable",
      Neutral: "average", Enemy: "uncomfortable", "Great Enemy": "very uncomfortable", Debilitated: "at its weakest" },
    EVENT: { marriage: "a good time for marriage, engagement or a serious relationship to start", career: "a job change, promotion, new job or a big career move",
      wealth: "income rise, savings or a financial gain", children: "childbirth or good news about children", education: "admission, exam success or completing a degree",
      property: "buying a house, land or vehicle", foreign: "foreign travel, a move abroad or work linked to foreign places",
      health: "health needs care - illness, a hospital visit or a check-up finding something is possible", father: "important events for your father (career, health or family matters)",
      mother: "important events for your mother or home", siblings: "events involving brothers/sisters", mind: "a phase that strongly affects your mood and peace of mind",
      govt_authority: "a government job, authority, award or public recognition", accidents_surgery: "risk of an accident, injury or surgery - drive carefully and avoid risks",
      love: "a romantic phase - a relationship starting, deepening or (if the period is hard) ending", spirituality: "spiritual growth, pilgrimage or a strong interest in meditation/religion",
      litigation: "disputes, debts or conflicts - avoid lending money and legal fights" },
    AREA: { marriage: "Marriage / spouse", career: "Career / job / status", wealth: "Money / gains", children: "Children", education: "Education",
      property: "Property / home / vehicle", foreign: "Foreign travel / settlement", health: "Health", father: "Father", mother: "Mother", siblings: "Siblings",
      mind: "Mind / emotional stability", govt_authority: "Government job / authority / fame", accidents_surgery: "Accidents / surgery / sudden events",
      love: "Love & relationships", spirituality: "Spiritual growth", litigation: "Disputes / debts / enemies" },
    DUR: { Sun: "about a month", Moon: "2-3 days", Mars: "about 6 weeks", Mercury: "3-4 weeks", Jupiter: "about a year", Venus: "about a month",
      Saturn: "about 2.5 years", Rahu: "about 1.5 years", Ketu: "about 1.5 years" },
    GOOD: { 1: "fresh energy and recognition", 2: "money comes in and family is happy", 3: "courage, success through effort, wins over rivals",
      4: "comfort at home, gains in property or vehicles", 5: "good ideas, happiness from children or love", 6: "victory over rivals, health improves, debts reduce",
      7: "good for spouse, partnerships and travel", 8: "unexpected gains", 9: "luck helps you, blessings, good travel", 10: "career success and status",
      11: "income and gains, wishes fulfilled", 12: "money spent on good things, peaceful sleep" },
    BAD: { 1: "tiredness, stress or health trouble", 2: "expenses, family friction, harsh words", 3: "low courage, trouble with siblings",
      4: "unrest at home, mother's health or vehicle trouble", 5: "worry about studies/children, poor decisions", 6: "illness, enemies or debts trouble you",
      7: "friction with spouse or partners, travel trouble", 8: "obstacles, health scares, sudden setbacks", 9: "bad luck, friction with father or teachers",
      10: "work pressure and problems at the job", 11: "gains get delayed", 12: "expenses, losses, poor sleep" },
    VERDICT: { strong: "Strong. The chart clearly supports this area; it is likely to go well.", moderate: "Mixed. It happens, but with some effort, delay or compromise.",
      weak: "Weak. Expect obstacles here - delays, struggle or dissatisfaction.", "very weak": "Very weak. A difficult area in your chart - serious problems are likely, or it may not happen the way you hope.",
      vulnerable: "Sensitive area. You are vulnerable here - be careful and act early (check-ups, caution, no risks).",
      protected: "Well protected. Problems in this area stay limited.", avgprot: "Average protection. Some trouble is possible but manageable." },
    VWORD: { strong: "strong", moderate: "moderate", weak: "weak", "very weak": "very weak" },
    TONE: { good: "mostly good - growth and support", benweak: "good intentions but weak delivery - results come with effort",
      hard: "testing - struggles and pressure; work hard and be careful", malmixed: "mixed - gains come with stress or a price", mixed: "mixed - depends on what you do" },
    TONEWORD: { good: "good", mixed: "mixed", hard: "hard" },
    t: {
      occBen: (p, x, h) => `${p} sits in this area: brings ${x} to ${h}.`,
      occMal: (p, x, h) => `${p} sits in this area: expect ${x} in matters of ${h}.`,
      aspBen: (p, x) => `${p} looks at this area: adds ${x}.`, aspMal: (p, x) => `${p} looks at this area: adds ${x}.`,
      lord: (p, d, s, h) => `${p}, the planet in charge of this area, is ${d} and sits in your house of ${s} - so this area gets tied to ${h}.`,
      lordDus: (p, s) => `Its ruling planet ${p} sits in a difficult house (${s}) - expect struggle, delay or worry here.`,
      lordGood: p => `Its ruling planet ${p} is well placed - this area gets steady support.`,
      karaka: (p, lvl, s, w) => `${p}, the natural sign-giver for this area, is ${lvl} overall (${s} good points, ${w} bad).`,
      lvl: { strong: "strong", ok: "okay", weak: "weak" },
      savGood: n => `This house scores high (${n} points) - results here come more easily.`, savWeak: n => `This house scores low (${n} points) - results here need extra effort.`,
      vargaLord: (d, dg, ok) => `In the detailed chart for this area (D${d}), the ruler is ${dg} - ${ok ? "the deeper promise holds up" : "the deeper promise is weaker than it looks"}.`,
      vargaHouseBad: d => `In the detailed chart (D${d}) the ruler falls in a difficult house - hidden problems or delays.`,
      vargaHouseGood: d => `In the detailed chart (D${d}) the ruler is well placed.`,
      vargaKar: (d, p, dg) => `In the detailed chart (D${d}), ${p} is ${dg}.`,
      moonMal: ps => `Seen from your Moon (your mind), ${ps} press on this area - it can feel emotionally stressful.`,
      sureHigh: "Strong chance: both your dasha and the slow planets (Jupiter + Saturn) point to it.",
      sureMed: "Possible: some signs point to it, not all.", sureLow: "Weak chance: only the dasha points to it.",
      win: (ev, peak, md, ad, sure, past) => `${ev[0].toUpperCase() + ev.slice(1)}, most likely around ${peak} (during ${md}/${ad}). ${sure}${past ? " This is in the past - did something like this happen? If yes, the chart's timing is working for you." : ""}`,
      md: (p, topics, themes, tone) => `${p} period: life focuses on ${topics}. Themes of ${themes}. Overall ${tone}.`,
      adBad: (ad, rel, md) => ` ${ad} sits ${rel}th from ${md}, so the two pull in different directions - friction, delays or health strain.`,
      adGood: (ad, md) => ` ${ad} and ${md} work well together, so results flow smoothly.`,
      ad: (topics, tone, extra) => `${topics} come into focus - ${tone}.${extra}`,
      now: (md, mdEnd, ad, adEnd, mdText, adText) => `You are in ${md} mahadasha (till ${mdEnd}) and ${ad} antardasha (till ${adEnd}). ${mdText} Right now: ${adText}`,
      str: (p, lvl, themes, owns, ok) => `${p} is ${lvl}. What this means for you: ${themes}, and the parts of life ${p} runs in your chart (${owns}), ${ok ? "work well and give results without much struggle" : "need extra effort; results come late or only partly"}.`,
      strLvl: { strong: "strong", enough: "strong enough", slight: "slightly weak", weak: "weak" },
      sav: { weak: "needs extra effort", average: "average", good: "comes easily" },
      trGood: x => `Good for you now: ${x}.`, trBad: x => `Not easy now: ${x}.`, vedha: ps => ` But ${ps} blocks it, so the good effect is reduced.`,
      bGoodHi: " Your chart supports it well, so you feel the good clearly.", bGoodLo: " Your chart gives it little support, so the good stays small.",
      bBadHi: " Your chart supports this planet, so the trouble stays mild.", bBadLo: " Your chart gives it little support, so you may feel it more.",
      lasts: d => ` Lasts ${d}.`,
      satNone: "Saturn is not pressuring your Moon right now - no Sade Sati or Dhaiya. ",
      sade: { 12: "Sade Sati phase 1 (rising) - expenses, restlessness", 1: "Sade Sati phase 2 (peak) - pressure on mind/body, hard lessons",
        2: "Sade Sati phase 3 (setting) - finances/family strain easing", 4: "Kantaka Shani (4th from Moon) - home and peace of mind disturbed",
        8: "Ashtama Shani (8th from Moon) - obstacles, health, sudden setbacks" },
      debNo: (p, a) => `${p} stays weak - its areas (${a}) need effort.`, debYes: (p, a) => `${p} starts weak but recovers - early struggle, later rise in ${a}.`,
      yActive: r => `You get this: ${r}.`, yWeak: r => `You get this only partly: ${r}.`, yCanc: r => `Cancelled - don't expect: ${r}.`,
      dNo: "You don't have this.", dReduced: e => `Present but reduced: ${e} - milder than usual.`, dYes: e => `Present: ${e}.`,
      yogas: ys => `Working yogas: ${ys}.`, noYogas: "No major yoga works fully; the strong ones are weakened or cancelled.",
      doshas: ds => `Doshas that are fully active: ${ds}.`, noDoshas: "No dosha is fully active (any present are reduced by cancellations).",
    },
    RESULT: {},
  };

  const hi = {
    list: listHi,
    planet: p => ({ Sun: "Surya", Moon: "Chandra", Mars: "Mangal", Mercury: "Budh", Jupiter: "Guru", Venus: "Shukra", Saturn: "Shani", Rahu: "Rahu", Ketu: "Ketu" }[p] || p),
    sign: s => ({ Aries: "Mesh", Taurus: "Vrishabh", Gemini: "Mithun", Cancer: "Kark", Leo: "Singh", Virgo: "Kanya", Libra: "Tula", Scorpio: "Vrishchik",
      Sagittarius: "Dhanu", Capricorn: "Makar", Aquarius: "Kumbh", Pisces: "Meen" }[s] || s),
    HOUSE: { 1: "aapka sharir, sehat, roop aur confidence", 2: "paisa-bachat, parivaar aur aapki boli", 3: "himmat, apni mehnat, bhai-behen aur chhoti yatra",
      4: "ghar, maa, property, gaadi aur mann ki shanti", 5: "padhai, buddhi, bachche, prem aur creativity", 6: "naukri, competition, karz, bimari aur dushman",
      7: "shaadi, jeevansathi aur business partner", 8: "achanak ghatnayein, sasural ka paisa, raaz, operation aur lambi sehat",
      9: "kismat, pita, guru, dharm aur lambi yatra", 10: "career, kaam, naam aur pad", 11: "kamai, munafa, dost aur ichhayein poori hona",
      12: "kharche, videsh, neend, akelapan aur adhyatm" },
    SHORT: { 1: "sharir & sehat", 2: "paisa & parivaar", 3: "himmat & bhai-behen", 4: "ghar & maa", 5: "padhai, bachche & prem", 6: "naukri, karz & bimari",
      7: "shaadi & partner", 8: "achanak ghatnayein", 9: "kismat & pita", 10: "career & pad", 11: "kamai & labh", 12: "kharche & videsh" },
    PLANET: { Sun: "confidence, pita, sarkar aur adhikar", Moon: "mann, bhavnayein, maa aur public image", Mars: "energy, himmat, property, bhai aur gussa",
      Mercury: "baat-cheet, padhai, business aur tez dimaag", Jupiter: "gyaan, paise ki badhat, bachche, guru aur (ladkiyon ke liye) pati",
      Venus: "prem, shaadi, sukh-suvidha, sundarta, gaadi aur kala", Saturn: "mehnat, anushasan, deri, naukar aur lambe samay ke nateeje",
      Rahu: "mahatvakanksha, videsh, technology, achanak aur anokhi ghatnayein", Ketu: "vairagya, adhyatm, research aur achanak toot" },
    MAL: { Sun: "ego ki takkar aur haavi hone wala ravaiya", Mars: "behas, gussa ya garmi", Saturn: "deri, gambhirta, bhaari zimmedari (nateeje der se, par tikau)",
      Rahu: "uljhan, anokhi situations, bechaini", Ketu: "asantosh, doori ya laga-av ki kami", Moon: "bhavnaon ka utaar-chadhaav", Mercury: "mile-jule nateeje" },
    BEN: { Jupiter: "suraksha, samajh aur badhat", Venus: "mel-jol, prem aur sukh", Mercury: "achhi baat-cheet aur samajhdaar faisle", Moon: "dekhbhaal aur bhavnatmak sahara" },
    DIG: { Exalted: "sabse majboot (uchch)", Moolatrikona: "bahut majboot", Own: "majboot (apne ghar mein)", "Great Friend": "aaraam mein", Friend: "kaafi aaraam mein",
      Neutral: "average", Enemy: "asahaj", "Great Enemy": "bahut asahaj", Debilitated: "sabse kamzor (neech)" },
    EVENT: { marriage: "shaadi, sagai ya gambhir rishta shuru hone ka achha samay", career: "naukri badalna, promotion, nayi naukri ya career mein bada kadam",
      wealth: "kamai badhna, bachat ya paise ka labh", children: "santan ka janm ya bachchon se achhi khabar", education: "admission, exam mein safalta ya degree poori hona",
      property: "ghar, zameen ya gaadi khareedna", foreign: "videsh yatra, videsh jaana ya videsh se juda kaam",
      health: "sehat ka dhyan rakhna zaroori - bimari, hospital ya check-up mein kuch nikalna sambhav", father: "pita ke liye zaroori ghatnayein (career, sehat ya parivaar)",
      mother: "maa ya ghar se judi zaroori ghatnayein", siblings: "bhai-behen se judi ghatnayein", mind: "aisa daur jo mood aur mann ki shanti par gehra asar daale",
      govt_authority: "sarkari naukri, adhikar, sammaan ya public pehchaan", accidents_surgery: "durghatna, chot ya operation ka khatra - dhyan se chalayein, risk na lein",
      love: "prem ka daur - rishta shuru hona, gehra hona ya (mushkil daur ho to) khatam hona", spirituality: "adhyatmik badhat, teerth yatra ya dhyan/dharm mein ruchi",
      litigation: "jhagde, karz ya vivaad - udhaar dene aur court-kachehri se bachein" },
    AREA: { marriage: "Shaadi / jeevansathi", career: "Career / naukri / pad", wealth: "Paisa / labh", children: "Santan", education: "Padhai",
      property: "Property / ghar / gaadi", foreign: "Videsh yatra / basna", health: "Sehat", father: "Pita", mother: "Maa", siblings: "Bhai-behen",
      mind: "Mann / bhavnatmak sthirta", govt_authority: "Sarkari naukri / adhikar / naam", accidents_surgery: "Durghatna / operation / achanak ghatnayein",
      love: "Prem aur rishte", spirituality: "Adhyatmik badhat", litigation: "Jhagde / karz / dushman" },
    DUR: { Sun: "lagbhag 1 mahina", Moon: "2-3 din", Mars: "lagbhag 6 hafte", Mercury: "3-4 hafte", Jupiter: "lagbhag 1 saal", Venus: "lagbhag 1 mahina",
      Saturn: "lagbhag 2.5 saal", Rahu: "lagbhag 1.5 saal", Ketu: "lagbhag 1.5 saal" },
    GOOD: { 1: "nayi energy aur pehchaan", 2: "paisa aata hai, parivaar khush", 3: "himmat, mehnat se safalta, virodhiyon par jeet", 4: "ghar mein sukh, property ya gaadi ka labh",
      5: "achhe vichaar, bachchon ya prem se khushi", 6: "virodhiyon par jeet, sehat sudhre, karz ghate", 7: "jeevansathi, partnership aur yatra ke liye achha",
      8: "achanak labh", 9: "kismat saath de, aashirwad, achhi yatra", 10: "career mein safalta aur pad", 11: "kamai aur labh, ichhayein poori", 12: "achhe kaamon par kharch, sukoon ki neend" },
    BAD: { 1: "thakaan, tanaav ya sehat ki pareshani", 2: "kharche, parivaar mein khinchav, kadve shabd", 3: "himmat kam, bhai-behen se pareshani",
      4: "ghar mein ashanti, maa ki sehat ya gaadi ki dikkat", 5: "padhai/bachchon ki chinta, galat faisle", 6: "bimari, dushman ya karz pareshan karein",
      7: "jeevansathi ya partner se khinchav, yatra mein dikkat", 8: "rukaavatein, sehat ka darr, achanak jhatke", 9: "kismat saath na de, pita ya guru se khinchav",
      10: "kaam ka dabaav aur job mein dikkatein", 11: "labh mein deri", 12: "kharche, nuksaan, kharab neend" },
    VERDICT: { strong: "Majboot. Kundali is area ko saaf support karti hai; achha jaane ki sambhavna hai.", moderate: "Mila-jula. Hoga, par mehnat, deri ya samjhaute ke saath.",
      weak: "Kamzor. Yahan rukaavatein - deri, sangharsh ya asantosh - aa sakti hain.", "very weak": "Bahut kamzor. Kundali ka mushkil area - gambhir dikkatein sambhav, ya cheez aapki ummeed jaisi na ho.",
      vulnerable: "Naazuk area. Yahan aap kamzor hain - dhyan rakhein aur pehle se kadam uthayein (check-up, saavdhani, risk nahi).",
      protected: "Achhi suraksha. Is area ki dikkatein seemit rehti hain.", avgprot: "Average suraksha. Kuch dikkat ho sakti hai par sambhal jaayegi." },
    VWORD: { strong: "majboot", moderate: "mila-jula", weak: "kamzor", "very weak": "bahut kamzor" },
    TONE: { good: "zyaadatar achha - badhat aur sahara", benweak: "iraada achha par nateeja kamzor - mehnat se milega", hard: "pareeksha ka samay - sangharsh aur dabaav; mehnat karein aur saavdhan rahein",
      malmixed: "mila-jula - labh tanaav ya keemat ke saath", mixed: "mila-jula - aapke kaam par nirbhar" },
    TONEWORD: { good: "achha", mixed: "mila-jula", hard: "mushkil" },
    t: {
      occBen: (p, x, h) => `${p} is area mein baitha hai: ${h} mein ${x} laata hai.`, occMal: (p, x, h) => `${p} is area mein baitha hai: ${h} ke maamlon mein ${x} ki ummeed rakhein.`,
      aspBen: (p, x) => `${p} ki drishti is area par: ${x} jodta hai.`, aspMal: (p, x) => `${p} ki drishti is area par: ${x} jodta hai.`,
      lord: (p, d, s, h) => `${p}, jo is area ka swami hai, ${d} hai aur aapke ${s} wale ghar mein baitha hai - isliye yeh area ${h} se jud jaata hai.`,
      lordDus: (p, s) => `Iska swami ${p} mushkil ghar (${s}) mein hai - yahan sangharsh, deri ya chinta rahegi.`, lordGood: p => `Iska swami ${p} achhi jagah hai - is area ko lagaataar sahara milta hai.`,
      karaka: (p, lvl, s, w) => `${p}, is area ka swabhavik kaarak, kul milaakar ${lvl} hai (${s} achhe point, ${w} bure).`, lvl: { strong: "majboot", ok: "theek", weak: "kamzor" },
      savGood: n => `Is ghar ka score zyaada hai (${n} point) - yahan nateeje aasaani se milte hain.`, savWeak: n => `Is ghar ka score kam hai (${n} point) - yahan zyaada mehnat lagegi.`,
      vargaLord: (d, dg, ok) => `Is area ki detailed kundali (D${d}) mein swami ${dg} hai - ${ok ? "gehra vaada bhi majboot hai" : "gehra vaada dikhne se kamzor hai"}.`,
      vargaHouseBad: d => `Detailed kundali (D${d}) mein swami mushkil ghar mein hai - chhupi dikkatein ya deri.`, vargaHouseGood: d => `Detailed kundali (D${d}) mein swami achhi jagah hai.`,
      vargaKar: (d, p, dg) => `Detailed kundali (D${d}) mein ${p} ${dg} hai.`, moonMal: ps => `Aapke Chandra (mann) se dekhein to ${ps} is area par dabaav daalte hain - mann par bojh mehsoos ho sakta hai.`,
      sureHigh: "Pakki sambhavna: aapki dasha aur dheemi chaal wale grah (Guru + Shani) dono isi taraf ishara karte hain.", sureMed: "Sambhav: kuch sanket isi taraf hain, sab nahi.",
      sureLow: "Kam sambhavna: sirf dasha ishara karti hai.",
      win: (ev, peak, md, ad, sure, past) => `${ev[0].toUpperCase() + ev.slice(1)}, sabse zyaada sambhav ${peak} ke aas-paas (${md}/${ad} ke dauraan). ${sure}${past ? " Yeh beet chuka hai - kya aisa kuch hua tha? Agar haan, to kundali ki timing aap par kaam kar rahi hai." : ""}`,
      md: (p, topics, themes, tone) => `${p} ka daur: zindagi ka focus ${topics} par. Vishay: ${themes}. Kul milaakar ${tone}.`,
      adBad: (ad, rel, md) => ` ${ad} ${md} se ${rel}ve ghar mein hai, isliye dono alag disha mein kheenchte hain - khinchav, deri ya sehat par asar.`,
      adGood: (ad, md) => ` ${ad} aur ${md} saath achha kaam karte hain, isliye nateeje aasaani se aate hain.`,
      ad: (topics, tone, extra) => `${topics} par dhyan aata hai - ${tone}.${extra}`,
      now: (md, mdEnd, ad, adEnd, mdText, adText) => `Aap ${md} mahadasha (${mdEnd} tak) aur ${ad} antardasha (${adEnd} tak) mein hain. ${mdText} Abhi: ${adText}`,
      str: (p, lvl, themes, owns, ok) => `${p} ${lvl} hai. Aapke liye matlab: ${themes}, aur aapki kundali mein ${p} jin hisson ko chalata hai (${owns}), ${ok ? "achha chalte hain aur bina zyaada sangharsh ke nateeja dete hain" : "zyaada mehnat maangte hain; nateeje der se ya aadhe milte hain"}.`,
      strLvl: { strong: "majboot", enough: "kaafi majboot", slight: "thoda kamzor", weak: "kamzor" }, sav: { weak: "zyaada mehnat chahiye", average: "average", good: "aasaani se milta hai" },
      trGood: x => `Abhi aapke liye achha: ${x}.`, trBad: x => `Abhi aasaan nahi: ${x}.`, vedha: ps => ` Par ${ps} ise rok raha hai, isliye achha asar kam hai.`,
      bGoodHi: " Aapki kundali iska poora saath deti hai, isliye achha asar saaf dikhega.", bGoodLo: " Aapki kundali iska kam saath deti hai, isliye achha asar chhota rahega.",
      bBadHi: " Aapki kundali is grah ka saath deti hai, isliye dikkat halki rahegi.", bBadLo: " Aapki kundali iska kam saath deti hai, isliye asar zyaada mehsoos ho sakta hai.",
      lasts: d => ` Asar ${d} tak rahega.`, satNone: "Abhi Shani aapke Chandra par dabaav nahi daal raha - na Sade Sati, na Dhaiya. ",
      sade: { 12: "Sade Sati ka pehla charan - kharche, bechaini", 1: "Sade Sati ka beech ka charan - mann/sharir par dabaav, kade sabak", 2: "Sade Sati ka aakhri charan - paise/parivaar ka dabaav kam ho raha",
        4: "Kantaka Shani (Chandra se 4tha) - ghar aur mann ki shanti bhang", 8: "Ashtama Shani (Chandra se 8va) - rukaavatein, sehat, achanak jhatke" },
      debNo: (p, a) => `${p} kamzor rehta hai - iske area (${a}) mehnat maangte hain.`, debYes: (p, a) => `${p} kamzor shuru hota hai par sambhal jaata hai - pehle sangharsh, baad mein ${a} mein unnati.`,
      yActive: r => `Aapko yeh milta hai: ${r}.`, yWeak: r => `Yeh aadha hi milta hai: ${r}.`, yCanc: r => `Radd ho gaya - ummeed na rakhein: ${r}.`,
      dNo: "Yeh aapki kundali mein nahi hai.", dReduced: e => `Hai par kamzor: ${e} - aam se halka.`, dYes: e => `Hai: ${e}.`,
      yogas: ys => `Kaam karne wale yog: ${ys}.`, noYogas: "Koi bada yog poori tarah kaam nahi karta; majboot yog kamzor ya radd hain.",
      doshas: ds => `Poori tarah active dosh: ${ds}.`, noDoshas: "Koi dosh poori tarah active nahi (jo hain, unke asar kam ho chuke hain).",
    },
    RESULT: {
      "fame, intelligence, lasting reputation, victory over rivals": "naam, buddhi, tikau pratishtha, virodhiyon par jeet", "wealth, vehicles, generosity, comforts": "dhan, gaadi, udaarta, sukh",
      "self-earned wealth, good intellect and reputation": "apni kamai ka dhan, achhi buddhi aur naam", "good health, pleasing personality, renunciation late in life": "achhi sehat, aakarshak vyaktitva, umar ke saath vairagya",
      "poverty, sorrow, dependence, mental unrest - if not cancelled": "garibi, dukh, nirbharta, mann ki ashanti - agar radd na ho", "king-like, eloquent, balanced, prosperous": "raja jaisa, achha vakta, santulit, samriddh",
      "truthful, balanced; results follow the nature of the planet (benefic good, malefic mixed)": "sachcha, santulit; nateeje grah ke swabhav par", "skilful, charitable, happy; results follow the planet's nature": "kushal, daani, khush; nateeje grah ke swabhav par",
      "intelligence, skill, good reputation": "buddhi, hunar, achha naam", "earning through trade/enterprise; can indicate harshness to mother": "vyapaar/udyam se kamai; maa ke saath kathorta bhi dikha sakta hai",
      "leadership, ministership, comfort, longevity": "netritva, oocha pad, sukh, lambi umar", "spotless reputation, ethical conduct, prosperity": "bedaag naam, naitik aacharan, samriddhi",
      "ups and downs of fortune like a cart wheel": "kismat mein gaadi ke pahiye jaise utaar-chadhaav", "steady accumulation of wealth": "dheere-dheere dhan jamaa hona",
      "a single planet that gives raja yoga in its dasha": "ek hi grah jo apni dasha mein raj yog deta hai", "rise in status, authority, success - timed by dashas of these planets": "pad, adhikar aur safalta mein badhat - in grahon ki dasha mein",
      "wealth accumulation in the periods of these planets": "in grahon ke daur mein dhan jamaa hona", "success arising out of adversity / others' loss": "mushkil se nikli safalta",
      "learning, eloquence, poetry, fame in scholarship": "vidya, vaakpatuta, kavita, gyaan mein naam", "wealth, nobility, fortune": "dhan, khaandaani pratishtha, kismat",
      "protection, health, prosperity for that point": "suraksha, sehat, samriddhi", "pressure, obstacles and health issues for that point": "dabaav, rukaavatein aur sehat ki dikkat",
      "great fortune, long life, fame": "badi kismat, lambi umar, naam", "fame across the four seas, wealth, longevity": "door-door tak naam, dhan, lambi umar",
      "courage, command, land, martial success": "himmat, netritva, zameen, sangharsh mein jeet", "intellect, eloquence, business skill": "buddhi, vaakpatuta, business ka hunar",
      "wisdom, righteousness, respect": "gyaan, dharm, sammaan", "luxury, beauty, spouse, vehicles, arts": "aishwarya, sundarta, jeevansathi, gaadi, kala",
      "authority over many, organisational power, wealth via labour/masses": "kai logon par adhikar, sangathan ki shakti, mehnat/janta se dhan",
      "great prosperity and status": "badi samriddhi aur pad", "struggles, enemies, fluctuations": "sangharsh, dushman, utaar-chadhaav", "fluctuating fortune; courage-driven gains": "badalti kismat; himmat se labh",
      "friction, delay or strain in marriage; Mars energy needs a channel": "shaadi mein khinchav, deri ya tanaav; Mangal ki urja ko sahi disha chahiye",
      "phases of obstruction followed by sudden rise; never used alone to predict events": "rukaavat ke daur, phir achanak unnati",
      "obstacles linked to father/ancestors, progeny delays, fortune blocked until remedies": "pita/poorvajon se judi rukaavatein, santan mein deri, kismat ruki hui",
      "early-life health/family disturbances per pada; mostly a birth-time ritual concern": "bachpan mein sehat/parivaar ki dikkat; zyaadatar janm ke samay ki shanti ka vishay",
      "eclipse of Sun: father, ego, authority, health": "Surya grahan: pita, ego, adhikar, sehat", "eclipse of Moon: anxiety, mother, emotional instability": "Chandra grahan: chinta, maa, bhavnatmak asthirta",
      "ethics/guru/children issues, unorthodox beliefs": "naitikta/guru/bachchon ki dikkat, alag soch", "delays, karmic burdens": "deri, karmic bojh",
      "anger, accidents, impulsive acts": "gussa, durghatna, jaldbaazi", "depressive tendencies, emotional heaviness, delays": "udaasi, mann bhaari, deri",
    },
  };

  const hd = {
    list: listHd,
    planet: p => ({ Sun: "सूर्य", Moon: "चंद्र", Mars: "मंगल", Mercury: "बुध", Jupiter: "गुरु", Venus: "शुक्र", Saturn: "शनि", Rahu: "राहु", Ketu: "केतु" }[p] || p),
    sign: s => ({ Aries: "मेष", Taurus: "वृषभ", Gemini: "मिथुन", Cancer: "कर्क", Leo: "सिंह", Virgo: "कन्या", Libra: "तुला", Scorpio: "वृश्चिक",
      Sagittarius: "धनु", Capricorn: "मकर", Aquarius: "कुंभ", Pisces: "मीन" }[s] || s),
    HOUSE: { 1: "आपका शरीर, सेहत, रूप और आत्मविश्वास", 2: "धन-बचत, परिवार और आपकी वाणी", 3: "साहस, अपनी मेहनत, भाई-बहन और छोटी यात्राएँ",
      4: "घर, माँ, संपत्ति, वाहन और मन की शांति", 5: "पढ़ाई, बुद्धि, संतान, प्रेम और रचनात्मकता", 6: "नौकरी, प्रतियोगिता, कर्ज़, बीमारी और शत्रु",
      7: "विवाह, जीवनसाथी और व्यापारिक साझेदार", 8: "अचानक घटनाएँ, ससुराल का धन, रहस्य, ऑपरेशन और लंबी सेहत",
      9: "भाग्य, पिता, गुरु, धर्म और लंबी यात्राएँ", 10: "करियर, काम, नाम और पद", 11: "आय, लाभ, मित्र और इच्छाओं की पूर्ति",
      12: "खर्च, विदेश, नींद, एकांत और आध्यात्म" },
    SHORT: { 1: "शरीर व सेहत", 2: "धन व परिवार", 3: "साहस व भाई-बहन", 4: "घर व माँ", 5: "पढ़ाई, संतान व प्रेम", 6: "नौकरी, कर्ज़ व बीमारी",
      7: "विवाह व साझेदार", 8: "अचानक घटनाएँ", 9: "भाग्य व पिता", 10: "करियर व पद", 11: "आय व लाभ", 12: "खर्च व विदेश" },
    PLANET: { Sun: "आत्मविश्वास, पिता, सरकार और अधिकार", Moon: "मन, भावनाएँ, माँ और सार्वजनिक छवि", Mars: "ऊर्जा, साहस, संपत्ति, भाई और क्रोध",
      Mercury: "बातचीत, पढ़ाई, व्यापार और तेज़ बुद्धि", Jupiter: "ज्ञान, धन वृद्धि, संतान, गुरु और (स्त्रियों के लिए) पति",
      Venus: "प्रेम, विवाह, सुख-सुविधा, सुंदरता, वाहन और कला", Saturn: "मेहनत, अनुशासन, देरी, सेवक और लंबे समय के परिणाम",
      Rahu: "महत्वाकांक्षा, विदेश, तकनीक, अचानक और असामान्य घटनाएँ", Ketu: "वैराग्य, आध्यात्म, शोध और अचानक टूटन" },
    MAL: { Sun: "अहं का टकराव और हावी होने वाला रवैया", Mars: "बहस, क्रोध या तनाव", Saturn: "देरी, गंभीरता, भारी ज़िम्मेदारी (परिणाम देर से पर टिकाऊ)",
      Rahu: "उलझन, असामान्य स्थितियाँ, बेचैनी", Ketu: "असंतोष, दूरी या लगाव की कमी", Moon: "भावनाओं का उतार-चढ़ाव", Mercury: "मिले-जुले परिणाम" },
    BEN: { Jupiter: "सुरक्षा, समझ और वृद्धि", Venus: "मेल, प्रेम और सुख", Mercury: "अच्छी बातचीत और समझदार निर्णय", Moon: "देखभाल और भावनात्मक सहारा" },
    DIG: { Exalted: "सबसे बलवान (उच्च)", Moolatrikona: "बहुत बलवान", Own: "बलवान (अपने घर में)", "Great Friend": "सहज", Friend: "काफ़ी सहज",
      Neutral: "सामान्य", Enemy: "असहज", "Great Enemy": "बहुत असहज", Debilitated: "सबसे कमज़ोर (नीच)" },
    EVENT: { marriage: "विवाह, सगाई या गंभीर रिश्ता शुरू होने का अच्छा समय", career: "नौकरी बदलना, पदोन्नति, नई नौकरी या करियर में बड़ा कदम",
      wealth: "आय बढ़ना, बचत या धन लाभ", children: "संतान का जन्म या बच्चों से अच्छी खबर", education: "प्रवेश, परीक्षा में सफलता या डिग्री पूरी होना",
      property: "घर, ज़मीन या वाहन खरीदना", foreign: "विदेश यात्रा, विदेश जाना या विदेश से जुड़ा काम",
      health: "सेहत का ध्यान ज़रूरी - बीमारी, अस्पताल या जाँच में कुछ निकलना संभव", father: "पिता के लिए महत्वपूर्ण घटनाएँ (करियर, सेहत या परिवार)",
      mother: "माँ या घर से जुड़ी महत्वपूर्ण घटनाएँ", siblings: "भाई-बहन से जुड़ी घटनाएँ", mind: "ऐसा दौर जो मन और शांति पर गहरा असर डाले",
      govt_authority: "सरकारी नौकरी, अधिकार, सम्मान या सार्वजनिक पहचान", accidents_surgery: "दुर्घटना, चोट या ऑपरेशन का खतरा - सावधानी से चलें, जोखिम न लें",
      love: "प्रेम का दौर - रिश्ता शुरू होना, गहरा होना या (कठिन दौर हो तो) खत्म होना", spirituality: "आध्यात्मिक उन्नति, तीर्थ यात्रा या ध्यान/धर्म में रुचि",
      litigation: "झगड़े, कर्ज़ या विवाद - उधार देने और मुकदमेबाज़ी से बचें" },
    AREA: { marriage: "विवाह / जीवनसाथी", career: "करियर / नौकरी / पद", wealth: "धन / लाभ", children: "संतान", education: "शिक्षा",
      property: "संपत्ति / घर / वाहन", foreign: "विदेश यात्रा / बसना", health: "स्वास्थ्य", father: "पिता", mother: "माँ", siblings: "भाई-बहन",
      mind: "मन / भावनात्मक स्थिरता", govt_authority: "सरकारी नौकरी / अधिकार / नाम", accidents_surgery: "दुर्घटना / ऑपरेशन / अचानक घटनाएँ",
      love: "प्रेम और रिश्ते", spirituality: "आध्यात्मिक उन्नति", litigation: "झगड़े / कर्ज़ / शत्रु" },
    DUR: { Sun: "लगभग 1 महीना", Moon: "2-3 दिन", Mars: "लगभग 6 हफ़्ते", Mercury: "3-4 हफ़्ते", Jupiter: "लगभग 1 साल", Venus: "लगभग 1 महीना",
      Saturn: "लगभग 2.5 साल", Rahu: "लगभग 1.5 साल", Ketu: "लगभग 1.5 साल" },
    GOOD: { 1: "नई ऊर्जा और पहचान", 2: "धन आता है, परिवार खुश", 3: "साहस, मेहनत से सफलता, विरोधियों पर जीत", 4: "घर में सुख, संपत्ति या वाहन लाभ",
      5: "अच्छे विचार, संतान या प्रेम से खुशी", 6: "विरोधियों पर जीत, सेहत सुधरे, कर्ज़ घटे", 7: "जीवनसाथी, साझेदारी और यात्रा के लिए अच्छा",
      8: "अचानक लाभ", 9: "भाग्य साथ दे, आशीर्वाद, अच्छी यात्रा", 10: "करियर में सफलता और पद", 11: "आय और लाभ, इच्छाएँ पूरी", 12: "अच्छे कामों पर खर्च, सुकून की नींद" },
    BAD: { 1: "थकान, तनाव या सेहत की परेशानी", 2: "खर्च, परिवार में खिंचाव, कड़वे शब्द", 3: "साहस कम, भाई-बहन से परेशानी",
      4: "घर में अशांति, माँ की सेहत या वाहन की दिक्कत", 5: "पढ़ाई/संतान की चिंता, गलत निर्णय", 6: "बीमारी, शत्रु या कर्ज़ परेशान करें",
      7: "जीवनसाथी या साझेदार से खिंचाव, यात्रा में दिक्कत", 8: "रुकावटें, सेहत का डर, अचानक झटके", 9: "भाग्य साथ न दे, पिता या गुरु से खिंचाव",
      10: "काम का दबाव और नौकरी में दिक्कतें", 11: "लाभ में देरी", 12: "खर्च, नुकसान, खराब नींद" },
    VERDICT: { strong: "बलवान। कुंडली इस क्षेत्र का साफ़ साथ देती है; अच्छा जाने की संभावना है।", moderate: "मिला-जुला। होगा, पर मेहनत, देरी या समझौते के साथ।",
      weak: "कमज़ोर। यहाँ रुकावटें - देरी, संघर्ष या असंतोष - आ सकती हैं।", "very weak": "बहुत कमज़ोर। कुंडली का कठिन क्षेत्र - गंभीर दिक्कतें संभव, या बात आपकी उम्मीद जैसी न हो।",
      vulnerable: "नाज़ुक क्षेत्र। यहाँ आप कमज़ोर हैं - ध्यान रखें और पहले से कदम उठाएँ (जाँच, सावधानी, जोखिम नहीं)।",
      protected: "अच्छी सुरक्षा। इस क्षेत्र की दिक्कतें सीमित रहती हैं।", avgprot: "सामान्य सुरक्षा। कुछ दिक्कत हो सकती है पर संभल जाएगी।" },
    VWORD: { strong: "बलवान", moderate: "मिला-जुला", weak: "कमज़ोर", "very weak": "बहुत कमज़ोर" },
    TONE: { good: "ज़्यादातर अच्छा - वृद्धि और सहारा", benweak: "इरादा अच्छा पर परिणाम कमज़ोर - मेहनत से मिलेगा", hard: "परीक्षा का समय - संघर्ष और दबाव; मेहनत करें और सावधान रहें",
      malmixed: "मिला-जुला - लाभ तनाव या कीमत के साथ", mixed: "मिला-जुला - आपके कर्म पर निर्भर" },
    TONEWORD: { good: "अच्छा", mixed: "मिला-जुला", hard: "कठिन" },
    t: {
      occBen: (p, x, h) => `${p} इस क्षेत्र में बैठा है: ${h} में ${x} लाता है।`, occMal: (p, x, h) => `${p} इस क्षेत्र में बैठा है: ${h} के मामलों में ${x} की संभावना।`,
      aspBen: (p, x) => `${p} की दृष्टि इस क्षेत्र पर: ${x} जोड़ता है।`, aspMal: (p, x) => `${p} की दृष्टि इस क्षेत्र पर: ${x} जोड़ता है।`,
      lord: (p, d, s, h) => `${p}, जो इस क्षेत्र का स्वामी है, ${d} है और आपके ${s} वाले भाव में बैठा है - इसलिए यह क्षेत्र ${h} से जुड़ जाता है।`,
      lordDus: (p, s) => `इसका स्वामी ${p} कठिन भाव (${s}) में है - यहाँ संघर्ष, देरी या चिंता रहेगी।`, lordGood: p => `इसका स्वामी ${p} अच्छी जगह है - इस क्षेत्र को लगातार सहारा मिलता है।`,
      karaka: (p, lvl, s, w) => `${p}, इस क्षेत्र का स्वाभाविक कारक, कुल मिलाकर ${lvl} है (${s} अच्छी बातें, ${w} बुरी)।`, lvl: { strong: "बलवान", ok: "ठीक", weak: "कमज़ोर" },
      savGood: n => `इस भाव का अंक ऊँचा है (${n}) - यहाँ परिणाम आसानी से मिलते हैं।`, savWeak: n => `इस भाव का अंक कम है (${n}) - यहाँ ज़्यादा मेहनत लगेगी।`,
      vargaLord: (d, dg, ok) => `इस क्षेत्र की विस्तृत कुंडली (D${d}) में स्वामी ${dg} है - ${ok ? "गहरा वादा भी मज़बूत है" : "गहरा वादा दिखने से कमज़ोर है"}।`,
      vargaHouseBad: d => `विस्तृत कुंडली (D${d}) में स्वामी कठिन भाव में है - छिपी दिक्कतें या देरी।`, vargaHouseGood: d => `विस्तृत कुंडली (D${d}) में स्वामी अच्छी जगह है।`,
      vargaKar: (d, p, dg) => `विस्तृत कुंडली (D${d}) में ${p} ${dg} है।`, moonMal: ps => `आपके चंद्र (मन) से देखें तो ${ps} इस क्षेत्र पर दबाव डालते हैं - मन पर बोझ महसूस हो सकता है।`,
      sureHigh: "पक्की संभावना: आपकी दशा और धीमे ग्रह (गुरु + शनि) दोनों इसी ओर इशारा करते हैं।", sureMed: "संभव: कुछ संकेत इसी ओर हैं, सब नहीं।",
      sureLow: "कम संभावना: केवल दशा इशारा करती है।",
      win: (ev, peak, md, ad, sure, past) => `${ev}, सबसे ज़्यादा संभावना ${peak} के आसपास (${md}/${ad} के दौरान)। ${sure}${past ? " यह बीत चुका है - क्या ऐसा कुछ हुआ था? अगर हाँ, तो कुंडली की टाइमिंग आप पर काम कर रही है।" : ""}`,
      md: (p, topics, themes, tone) => `${p} का दौर: जीवन का ध्यान ${topics} पर। विषय: ${themes}। कुल मिलाकर ${tone}।`,
      adBad: (ad, rel, md) => ` ${ad} ${md} से ${rel}वें भाव में है, इसलिए दोनों अलग दिशा में खींचते हैं - खिंचाव, देरी या सेहत पर असर।`,
      adGood: (ad, md) => ` ${ad} और ${md} साथ अच्छा काम करते हैं, इसलिए परिणाम आसानी से आते हैं।`,
      ad: (topics, tone, extra) => `${topics} पर ध्यान आता है - ${tone}।${extra}`,
      now: (md, mdEnd, ad, adEnd, mdText, adText) => `आप ${md} महादशा (${mdEnd} तक) और ${ad} अंतर्दशा (${adEnd} तक) में हैं। ${mdText} अभी: ${adText}`,
      str: (p, lvl, themes, owns, ok) => `${p} ${lvl} है। आपके लिए मतलब: ${themes}, और आपकी कुंडली में ${p} जिन हिस्सों को चलाता है (${owns}), ${ok ? "अच्छे चलते हैं और बिना ज़्यादा संघर्ष के परिणाम देते हैं" : "ज़्यादा मेहनत माँगते हैं; परिणाम देर से या आधे मिलते हैं"}।`,
      strLvl: { strong: "बलवान", enough: "पर्याप्त बलवान", slight: "थोड़ा कमज़ोर", weak: "कमज़ोर" }, sav: { weak: "ज़्यादा मेहनत चाहिए", average: "सामान्य", good: "आसानी से मिलता है" },
      trGood: x => `अभी आपके लिए अच्छा: ${x}।`, trBad: x => `अभी आसान नहीं: ${x}।`, vedha: ps => ` पर ${ps} इसे रोक रहा है, इसलिए अच्छा असर कम है।`,
      bGoodHi: " आपकी कुंडली इसका पूरा साथ देती है, इसलिए अच्छा असर साफ़ दिखेगा।", bGoodLo: " आपकी कुंडली इसका कम साथ देती है, इसलिए अच्छा असर छोटा रहेगा।",
      bBadHi: " आपकी कुंडली इस ग्रह का साथ देती है, इसलिए दिक्कत हल्की रहेगी।", bBadLo: " आपकी कुंडली इसका कम साथ देती है, इसलिए असर ज़्यादा महसूस हो सकता है।",
      lasts: d => ` असर ${d} तक रहेगा।`, satNone: "अभी शनि आपके चंद्र पर दबाव नहीं डाल रहा - न साढ़ेसाती, न ढैया। ",
      sade: { 12: "साढ़ेसाती का पहला चरण - खर्च, बेचैनी", 1: "साढ़ेसाती का मध्य चरण - मन/शरीर पर दबाव, कड़े सबक", 2: "साढ़ेसाती का अंतिम चरण - धन/परिवार का दबाव कम हो रहा",
        4: "कंटक शनि (चंद्र से चौथा) - घर और मन की शांति भंग", 8: "अष्टम शनि (चंद्र से आठवाँ) - रुकावटें, सेहत, अचानक झटके" },
      debNo: (p, a) => `${p} कमज़ोर रहता है - इसके क्षेत्र (${a}) मेहनत माँगते हैं।`, debYes: (p, a) => `${p} कमज़ोर शुरू होता है पर संभल जाता है - पहले संघर्ष, बाद में ${a} में उन्नति।`,
      yActive: r => `आपको यह मिलता है: ${r}।`, yWeak: r => `यह आधा ही मिलता है: ${r}।`, yCanc: r => `रद्द हो गया - उम्मीद न रखें: ${r}।`,
      dNo: "यह आपकी कुंडली में नहीं है।", dReduced: e => `है पर कमज़ोर: ${e} - सामान्य से हल्का।`, dYes: e => `है: ${e}।`,
      yogas: ys => `काम करने वाले योग: ${ys}।`, noYogas: "कोई बड़ा योग पूरी तरह काम नहीं करता; बलवान योग कमज़ोर या रद्द हैं।",
      doshas: ds => `पूरी तरह सक्रिय दोष: ${ds}।`, noDoshas: "कोई दोष पूरी तरह सक्रिय नहीं (जो हैं, उनके असर कम हो चुके हैं)।",
    },
    RESULT: {},
  };
  hd.RESULT = {
      "fame, intelligence, lasting reputation, victory over rivals": "यश, बुद्धि, स्थायी प्रतिष्ठा, विरोधियों पर विजय", "wealth, vehicles, generosity, comforts": "धन, वाहन, उदारता, सुख",
      "self-earned wealth, good intellect and reputation": "अपनी कमाई का धन, अच्छी बुद्धि और नाम", "good health, pleasing personality, renunciation late in life": "अच्छी सेहत, आकर्षक व्यक्तित्व, उम्र के साथ वैराग्य",
      "poverty, sorrow, dependence, mental unrest - if not cancelled": "गरीबी, दुख, निर्भरता, मन की अशांति - यदि रद्द न हो", "king-like, eloquent, balanced, prosperous": "राजा समान, वाक्पटु, संतुलित, समृद्ध",
      "truthful, balanced; results follow the nature of the planet (benefic good, malefic mixed)": "सच्चा, संतुलित; परिणाम ग्रह के स्वभाव पर", "skilful, charitable, happy; results follow the planet's nature": "कुशल, दानी, प्रसन्न; परिणाम ग्रह के स्वभाव पर",
      "intelligence, skill, good reputation": "बुद्धि, कौशल, अच्छा नाम", "earning through trade/enterprise; can indicate harshness to mother": "व्यापार/उद्यम से आय; माँ के साथ कठोरता भी दिखा सकता है",
      "leadership, ministership, comfort, longevity": "नेतृत्व, ऊँचा पद, सुख, दीर्घायु", "spotless reputation, ethical conduct, prosperity": "बेदाग़ नाम, नैतिक आचरण, समृद्धि",
      "ups and downs of fortune like a cart wheel": "गाड़ी के पहिये जैसे भाग्य में उतार-चढ़ाव", "steady accumulation of wealth": "धीरे-धीरे धन संचय",
      "a single planet that gives raja yoga in its dasha": "एक ही ग्रह जो अपनी दशा में राजयोग देता है", "rise in status, authority, success - timed by dashas of these planets": "पद, अधिकार और सफलता में वृद्धि - इन ग्रहों की दशा में",
      "wealth accumulation in the periods of these planets": "इन ग्रहों के दौर में धन संचय", "success arising out of adversity / others' loss": "कठिनाई से निकली सफलता",
      "learning, eloquence, poetry, fame in scholarship": "विद्या, वाक्पटुता, काव्य, ज्ञान में यश", "wealth, nobility, fortune": "धन, कुलीनता, भाग्य",
      "protection, health, prosperity for that point": "सुरक्षा, सेहत, समृद्धि", "pressure, obstacles and health issues for that point": "दबाव, रुकावटें और सेहत की दिक्कत",
      "great fortune, long life, fame": "महान भाग्य, दीर्घायु, यश", "fame across the four seas, wealth, longevity": "दूर-दूर तक यश, धन, दीर्घायु",
      "courage, command, land, martial success": "साहस, नेतृत्व, भूमि, संघर्ष में विजय", "intellect, eloquence, business skill": "बुद्धि, वाक्पटुता, व्यापार कौशल",
      "wisdom, righteousness, respect": "ज्ञान, धर्म, सम्मान", "luxury, beauty, spouse, vehicles, arts": "ऐश्वर्य, सुंदरता, जीवनसाथी, वाहन, कला",
      "authority over many, organisational power, wealth via labour/masses": "अनेक लोगों पर अधिकार, संगठन शक्ति, मेहनत/जनता से धन",
      "great prosperity and status": "बड़ी समृद्धि और पद", "struggles, enemies, fluctuations": "संघर्ष, शत्रु, उतार-चढ़ाव", "fluctuating fortune; courage-driven gains": "बदलता भाग्य; साहस से लाभ",
      "friction, delay or strain in marriage; Mars energy needs a channel": "विवाह में खिंचाव, देरी या तनाव; मंगल की ऊर्जा को सही दिशा चाहिए",
      "phases of obstruction followed by sudden rise; never used alone to predict events": "रुकावट के दौर, फिर अचानक उन्नति",
      "obstacles linked to father/ancestors, progeny delays, fortune blocked until remedies": "पिता/पूर्वजों से जुड़ी रुकावटें, संतान में देरी, भाग्य रुका हुआ",
      "early-life health/family disturbances per pada; mostly a birth-time ritual concern": "बचपन में सेहत/परिवार की दिक्कत; मुख्यतः जन्म के समय की शांति का विषय",
      "eclipse of Sun: father, ego, authority, health": "सूर्य ग्रहण: पिता, अहं, अधिकार, सेहत", "eclipse of Moon: anxiety, mother, emotional instability": "चंद्र ग्रहण: चिंता, माँ, भावनात्मक अस्थिरता",
      "ethics/guru/children issues, unorthodox beliefs": "नैतिकता/गुरु/संतान की दिक्कत, अलग सोच", "delays, karmic burdens": "देरी, कर्म का बोझ",
      "anger, accidents, impulsive acts": "क्रोध, दुर्घटना, जल्दबाज़ी", "depressive tendencies, emotional heaviness, delays": "उदासी, मन भारी, देरी",
    };

  J.LANG = { en, hi, hd };
  if (typeof module !== "undefined") module.exports = J;
})(typeof window !== "undefined" ? window : globalThis);
